version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
  tpachat:
    container_name: tpachat
    image: yassinekaroui/tpachat
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - 8089:9090
