version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysqldb
  tpachat:
    container_name: tpachat
    image: tpachat
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - 8089:9090
