version: "3"
services:
  mysqldb:
         container_name: mysqldb
         image: mysql:8
         environment:
                 MYSQL_ROOT_PASSWORD: admin
         ports:
                 - 3306:3306
         volumes:
                 - /home/mysqldata:/var/lib/msql
  spring_app:
         image: shidono/tpachat
         container_name: achatproject
         restart : on-failure
         ports:
                 - 8089:8089
         depends_on:
                 - mysqldb
